name = "SSSynth"
uuid = "acafc109-a718-429c-b0e5-afd7f8c7ae46"
authors = ["Adam Wheeler <a.wheeler@columbia.edu>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Interpolations = "0.13"
julia = "1.0"
