name = "Korg"
uuid = "acafc109-a718-429c-b0e5-afd7f8c7ae46"
authors = ["Adam Wheeler <a.wheeler@columbia.edu>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

[compat]
Interpolations = "0.13"
NLsolve = "4.5"
julia = "1.0"
